#!/bin/bash

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

alias \
        sshconcordia="ssh -L 3306:eac353.encs.concordia.ca:3306 r_ichaud@login.encs.concordia.ca" \
        svenv="source venv/bin/activate"

# Colorize commands when possible.
alias \
        ls="ls -hN --color=auto --group-directories-first" \
        grep="grep --color=auto" \
        diff="diff --color=auto" \
        ccat="highlight --out-format=ansi"
